// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyAiNqBYoEofgkE_632LPfJrIgqJWC-PY1k',
      appId: '1:129561910299:web:ff3deaa623b36c77332cbe',
      messagingSenderId: '129561910299',
      projectId: 'lasagna-c9d25',
      authDomain: 'lasagna-c9d25.firebaseapp.com',
      storageBucket: 'lasagna-c9d25.appspot.com',
      measurementId: 'G-G6R6244R71',
      databaseURL: 'https://lasagna-c9d25-default-rtdb.firebaseio.com');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDQxVxMhkARGci3B4RVXygywDAwoBVERM',
    appId: '1:129561910299:android:536df5ce557a8613332cbe',
    messagingSenderId: '129561910299',
    projectId: 'lasagna-c9d25',
    storageBucket: 'lasagna-c9d25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-vg8GzRcddy7hwwdeahwFeuOGkIYjoeM',
    appId: '1:129561910299:ios:a0c058c629d188d3332cbe',
    messagingSenderId: '129561910299',
    projectId: 'lasagna-c9d25',
    storageBucket: 'lasagna-c9d25.appspot.com',
    iosClientId:
        '129561910299-14t1m8824ofnd7go2ao3g2hr1koet50m.apps.googleusercontent.com',
    iosBundleId: 'com.bastola.lasagnaApp',
  );
}
