// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('create a user account', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('create a user account', async function() {
    await driver.get("http://142.11.240.144:3000/")
    await driver.manage().window().setRect({ width: 974, height: 962 })
    await driver.findElement(By.css("flt-glass-pane")).click()
    await driver.findElement(By.css("flt-glass-pane")).click()
    await driver.findElement(By.css("flt-glass-pane")).click()
    await driver.findElement(By.css("flt-glass-pane")).click()
    await driver.findElement(By.css("flt-glass-pane")).click()
    await driver.findElement(By.css("flt-glass-pane")).click()
    await driver.findElement(By.css("flt-glass-pane")).click()
    await driver.findElement(By.css("flt-glass-pane")).click()
  })
})
